### PR TITLE
Made error message clearer, and included HTML Template file not found error check.

### LINKED ISSUE #1204: Incorrect error message
This error assumes that TypeScript is not installed, and hides whatever error may be firing instead.

https://github.com/fuse-box/fuse-box/blob/e9f84099b93030ffcea9291e9f86f2388e2b99ca/src/core/File.ts#L622

screen shot 2018-04-16 at 9 16 49 pm

### PR DESCRIPTION
**Pull request by jpike88**
fixes #1204, and also includes an import check for importing HTML files with the ng-template plugin.

### CODE REVIEW

**Comment by jpike88** [comment]
@nchanged hopefully this helps!

**Comment by jpike88** [comment]
Also, if you could make a release based on this that'd be sweet

File: src/core/File.ts [hunk 1]
```diff
@@ -451,6 +451,9 @@ export class File {
                 this.context.fuse.producer.addWarning('unresolved',
                     `Statement "${this.info.fuseBoxPath}" has failed to resolve in module "${this.collection && this.collection.name}"`);
             }
+            if (/\.html$/.test(this.info.fuseBoxPath)){
```
Comment (nchanged) [inline src/core/File.ts]: I don't think we need to need a special case for HTML. 
IT should be generic and message customised.

**Comment by jpike88** [comment]
I also wonder if it's worth converting line 452 to an error instead of a warning as well. What do you think?

File: src/core/File.ts [hunk 2]
```diff
@@ -450,6 +450,8 @@ export class File {
             if (/\.js$/.test(this.info.fuseBoxPath) && this.context.fuse && this.context.fuse.producer) {
```
Comment (nchanged) [inline src/core/File.ts]: I think it can be `jsx` too. Or other things that should be interpreted as assets

Comment (jpike88) [reply src/core/File.ts]: Line 454 catches all else statements, so .jsx will be caught. I wonder if all of them should be throwing an error?

Comment (nchanged) [reply src/core/File.ts]: Yeah, just jsx isn't an assets, it's a module ;-)

Comment (jpike88) [reply src/core/File.ts]: Done. Does it make sense for one to throw warnings and the else to throw errors? I would think that errors should always be thrown is something is missing?
