### PR TITLE
fix(Quantum): Prevent Quantum from creating empty chunks

### LINKED ISSUE #1297: Tiny chunk: 5 bytes
In my production build, a chunk of size 5 bytes is created.

Here is a content of the file:
```js
$fsx;
```

All of the logs for this chunk:
```
  → Create split bundle 3b2ebcd7 with entry point @firebase/firestore/dist/index.cjs.js

  → Render bundle 3b2ebcd7

  → Uglifying bundles/3b2ebcd7...
  → Using uglify-es because the target is greater than ES5 or es6 option is set
  → Done uglifying bundles/3b2ebcd7
  size:  5 Bytes, 25 Bytes (gzipped)
```

### PR DESCRIPTION
**Pull request by nchanged**
fixes #1297 #1184

### CODE REVIEW

File: src/tests/stubs/FuseTestEnv.ts [hunk 1]
```diff
@@ -151,6 +151,10 @@ export class FuseTestEnv {
 		return this.scripts.get(name);
 	}
 
+	public getScripts() {
```
Comment (merlinnot) [inline src/tests/stubs/FuseTestEnv.ts]: Why don't you just make a getter?

Comment (nchanged) [reply src/tests/stubs/FuseTestEnv.ts]: java background ;-))

Comment (merlinnot) [reply src/tests/stubs/FuseTestEnv.ts]: It's a public field anyways, so actually... what's the point of this method? :)
