### PR TITLE
fix(production): polyfill global

### LINKED ISSUE #1654: global not  polyfilled in browser runProd
Some packages that uses global (global.localStoreage etc) works in runDev  but global is undefined in runProd

### PR DESCRIPTION
**Pull request by Teoxoy**
fix #1654

Uses `globalThis` for modern browsers and [this polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#Examples) for those that don't have `globalThis`.

### CODE REVIEW

File: src/production/transformation/processTransformation.ts [hunk 1]
```diff
@@ -21,7 +21,7 @@ function onGlobal(node: Identifier, props: LocalContext) {
     }
     if (!props.globalInserted) {
       props.globalInserted = true;
-      props.insertions.push(`const global = {};`);
+      props.insertions.push(`const global = globalThis || self || window || global;`);
```
Comment (nchanged) [inline src/production/transformation/processTransformation.ts]: you actually need to check them for being undefined. Otherwise, it will throw an error
```
typeof window !== "undefined" ? window : ...
```

Comment (Teoxoy) [reply src/production/transformation/processTransformation.ts]: Why will it throw an error?

This works:
```js
let a = undefined
let b = undefined
let c = { prop: 6 }
let d = { prop2: 12 }
let g = a || b || c || d
// g = c
```

Comment (nchanged) [reply src/production/transformation/processTransformation.ts]: `let g = a || b || c || d`

this will throw ^ Since those variables are not defined

Comment (nchanged) [reply src/production/transformation/processTransformation.ts]: You can  open a debugger a type `global` you will see what I mean. Either way, I would just assign global to window if defined. If I am not mistaken that is being applied only for browser builds?

Comment (Teoxoy) [reply src/production/transformation/processTransformation.ts]: Oh yeah, I don't know what I was thinking.

Comment (Teoxoy) [reply src/production/transformation/processTransformation.ts]: Regarding your question, NodeJS has `global` and in workers you can't use `window` only `self`. So I think the order is good:
`globalThis` else `self` else `window` else `global`
